---
kind: pipeline
type: docker

steps:
  - name: build
    image: texlive/texlive:latest-with-cache
    commands:
      - latexmk

  - name: error log
    image: texlive/texlive:latest-with-cache
    commands:
      - cat main.log
    when:
      status: [failure]
